Remove unnecessary code (Django's underlying code already handles this)
zagaran/django-template pull request #9
Opened 2022-05-10 20:26 UTC by alvinsiu

2022-05-26 17:00 UTC, alvinsiu commented
Note: I've only reviewed a sampling of configurations, haven't actually tried deploying with these updates.

2022-05-27 00:37 UTC, zags requested changes

2022-05-27 00:37 UTC, zags commented on {{cookiecutter.project_slug}}/.platform/confighooks/predeploy/predeploy.sh
> +npm install
This should have a feature flag

2022-05-27 21:06 UTC, alvinsiu commented
@zags https://github.com/zagaran/django-template/pull/9/commits/b2130a2d57819f5bd83228b73c1a52d9ee5ceb4f

2022-05-30 19:05 UTC, zags approved these changes

2022-06-13 19:51 UTC, merged